version: "3.8"

services:
    admin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - "4444:80"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    db:
        image: mysql:latest
        container_name: db
        platform: linux/x86_64
        restart: "unless-stopped"
        volumes:
            - /usr/local/var/mysql_db:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
        command: --init-file /data/application/init.sql
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"

    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
        depends_on:
            - was
    was:
        build:
            context: ./
        container_name: was
        restart: "unless-stopped"
        depends_on:
            - db
            - redis

    redis:
        image: redis:latest
        container_name: redis
