version: "3.8"

services:
    admin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    db:
        image: mysql:latest
        container_name: db
        restart: "unless-stopped"
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        command: --init-file /data/application/init.sql
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/data/application/init.sql
            - /usr/local/var/mysql:/var/lib/mysql
    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
        depends_on:
            - was
    was:
        build:
            context: ./
        container_name: was
        restart: "unless-stopped"
        depends_on:
            - db
